---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka
  namespace: analytics
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/component: message-bus
automountServiceAccountToken: false
