---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: raccoon-system
resources:
  - ../../base
patches:
  - path: patches/deployment.yaml
    target:
      kind: Deployment
      name: raccoon-consumer
replicas:
  - name: raccoon-consumer
    count: 1
images:
  - name: raccoon-consumer
    newTag: latest
