extends: default
rules:
  line-length:
    max: 160
    level: warning
  document-start: disable
  trailing-spaces: enable
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false
