---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: PersistentVolumeClaim
      name: metabase-data
    patch: |
      - op: replace
        path: /spec/resources/requests/storage
        value: "1Gi"
  - target:
      kind: Deployment
      name: metabase
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "256Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "768Mi"
