---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stream-analytics-system
resources:
  - ../../base
replicas:
  - name: stream-analytics-server
    count: 2
images:
  - name: stream-analytics-server
    newTag: "0.0.0"
