---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nats
  namespace: data-management
  labels:
    app.kubernetes.io/name: nats
    app.kubernetes.io/part-of: stream-analytics
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nats
