---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nats
  namespace: data-management
  labels:
    app.kubernetes.io/name: nats
    app.kubernetes.io/component: messaging
    app.kubernetes.io/part-of: stream-analytics
    app.kubernetes.io/managed-by: argocd
automountServiceAccountToken: false
