---
apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: data-management
  labels:
    app.kubernetes.io/name: nats
    app.kubernetes.io/component: messaging
    app.kubernetes.io/part-of: market-raccoon
    app.kubernetes.io/managed-by: argocd
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: nats
  ports:
    - port: 4222
      name: client
      targetPort: client
      protocol: TCP
    - port: 8222
      name: monitor
      targetPort: monitor
      protocol: TCP
