---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: grafana
  namespace: observability-stack
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: dashboards
    app.kubernetes.io/part-of: stream-analytics
    app.kubernetes.io/managed-by: argocd
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
      app.kubernetes.io/component: dashboards
  maxUnavailable: 0
