---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  namespace: observability-stack
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: dashboards
    app.kubernetes.io/part-of: stream-analytics
    app.kubernetes.io/managed-by: argocd
automountServiceAccountToken: false
