---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metabase-data
  namespace: analytics
  labels:
    app.kubernetes.io/name: metabase
    app.kubernetes.io/component: bi-dashboard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
