---
apiVersion: v1
kind: Service
metadata:
  name: metabase
  namespace: analytics
  labels:
    app.kubernetes.io/name: metabase
    app.kubernetes.io/component: bi-dashboard
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: metabase
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
