---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stream-analytics-system
resources:
  - ../../base
patches:
  - path: patches/job.yaml
    target:
      kind: Job
      name: stream-analytics-migrate
images:
  - name: stream-analytics-migrate
    newTag: latest
