#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
cd "$ROOT_DIR"

REPORT_DIR=".context/evidence/subminute-rollout-gate"
WITH_SMOKE=0
WITH_RUNTIME_GATE=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --report-dir)
      REPORT_DIR="${2:?missing value for --report-dir}"
      shift 2
      ;;
    --with-smoke)
      WITH_SMOKE=1
      shift
      ;;
    --with-runtime-gate)
      WITH_RUNTIME_GATE=1
      shift
      ;;
    *)
      echo "unknown argument: $1" >&2
      echo "usage: $0 [--report-dir <path>] [--with-smoke] [--with-runtime-gate]" >&2
      exit 2
      ;;
  esac
done

timestamp="$(date -u +%Y%m%dT%H%M%SZ)"
run_dir="${REPORT_DIR}/${timestamp}"
runner_log="${run_dir}/runner.log"
report_file="${run_dir}/report.md"
latest_report="${REPORT_DIR}/latest.md"

mkdir -p "$run_dir"

steps=()
statuses=()
durations=()

run_step() {
  local name="$1"
  shift
  local start_ts end_ts duration status
  start_ts="$(date +%s)"
  echo "[subminute-gate] START ${name}: $*" | tee -a "$runner_log"
  if "$@" > >(tee "${run_dir}/${name}.log") 2>&1; then
    status="pass"
  else
    status="fail"
  fi
  end_ts="$(date +%s)"
  duration="$((end_ts - start_ts))"
  steps+=("$name")
  statuses+=("$status")
  durations+=("$duration")
  if [[ "$status" != "pass" ]]; then
    echo "[subminute-gate] FAIL ${name} (${duration}s)" | tee -a "$runner_log"
    return 1
  fi
  echo "[subminute-gate] PASS ${name} (${duration}s)" | tee -a "$runner_log"
}

write_report() {
  local status="$1"
  {
    echo "# Sub-Minute Rollout Gate Report"
    echo
    echo "- timestamp_utc: ${timestamp}"
    echo "- status: ${status}"
    echo "- with_smoke: ${WITH_SMOKE}"
    echo "- with_runtime_gate: ${WITH_RUNTIME_GATE}"
    echo
    echo "## Steps"
    echo
    echo "| Step | Status | Duration (s) | Log |"
    echo "|---|---|---:|---|"
    local i
    for i in "${!steps[@]}"; do
      echo "| ${steps[$i]} | ${statuses[$i]} | ${durations[$i]} | \`${steps[$i]}.log\` |"
    done
    echo
    echo "## Canary Matrix"
    echo
    echo "- rollback hard-off: \`subminute_rollout.enabled=false\` -> \`1s/5s\` bloqueados"
    echo "- scoped canary: \`enabled=true\` + allow-list \`venues[]\`/\`instruments[]\`"
    echo "- baseline intact: \`1m+\` continua disponivel"
    echo
    echo "## Notes"
    echo
    echo "- Generated by: \`scripts/test/util/subminute-rollout-gate.sh\`"
  } > "$report_file"
  cp "$report_file" "$latest_report"
}

echo "[subminute-gate] run directory: ${run_dir}" | tee -a "$runner_log"

run_step "processor-rollout-tests" go test ./cmd/processor -run 'TestSubMinuteRolloutGate_ScopedMatching|TestSubMinuteFilteringPublisher_BlocksSubMinuteAndCountsDrop|TestSubMinuteFilteringStores_BlockSubMinuteOnly'
run_step "server-rollout-tests" go test ./cmd/server -run 'TestSubMinuteFilteringRangeStore_BlocksSubMinuteAndAllowsHigherTF|TestSubMinuteFilteringRangeStore_ScopedAllowlistByVenueAndInstrument|TestSubMinuteFilteringCandleReader_BlocksSubMinuteRange|TestSubMinuteFilteringStatsReader_BlocksSubMinuteRange'
run_step "runtime-catchup-tests" go test ./internal/actors/aggregation/runtime -run 'TestProcessor_CatchUpSkipBookDeltaSkipsStaleBookDeltaWhenConfigured|TestProcessor_CatchUpSkipTradeSkipsStaleTradeWhenConfigured|TestProcessor_CatchUpSkipStatsSkipsStaleLiquidationWhenConfigured'

if [[ "$WITH_SMOKE" -eq 1 ]]; then
  run_step "smoke" make smoke
fi

if [[ "$WITH_RUNTIME_GATE" -eq 1 ]]; then
  run_step "runtime-gate" make runtime-gate
fi

write_report "pass"
echo "[subminute-gate] PASS report=${report_file}" | tee -a "$runner_log"
