---
apiVersion: v1
kind: Service
metadata:
  name: raccoon-server
  namespace: raccoon-system
  labels:
    app.kubernetes.io/name: raccoon-server
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: market-raccoon
    app.kubernetes.io/managed-by: argocd
spec:
  selector:
    app: raccoon-server
  ports:
    - port: 80
      name: service
      targetPort: service
      protocol: TCP
