---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: observability-stack-default
  namespace: observability-stack
  labels:
    app.kubernetes.io/part-of: stream-analytics
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {}
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - protocol: TCP
          port: 3000
  egress:
    - to:
        - podSelector: {}
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: stream-analytics-system
      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 8081
        - protocol: TCP
          port: 8082
        - protocol: TCP
          port: 8083
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: data-management
      ports:
        - protocol: TCP
          port: 8222
        - protocol: TCP
          port: 9363
        - protocol: TCP
          port: 9100
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: analytics
      ports:
        - protocol: TCP
          port: 9644
        - protocol: TCP
          port: 8081
