---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: observability-stack-default
  namespace: observability-stack
  labels:
    app.kubernetes.io/part-of: market-raccoon
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {}
  egress:
    - to:
        - podSelector: {}
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: raccoon-system
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: data-management
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
