---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: default-quota
  namespace: observability-stack
  labels:
    app.kubernetes.io/part-of: stream-analytics
    app.kubernetes.io/managed-by: argocd
spec:
  hard:
    requests.cpu: "2"
    requests.memory: "2Gi"
    limits.cpu: "4"
    limits.memory: "8Gi"
    pods: "20"
    persistentvolumeclaims: "5"
