---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: data-management
resources:
  - ../../base
patches:
  - path: patches/statefulset.yaml
    target:
      kind: StatefulSet
      name: timescaledb
images:
  - name: timescale/timescaledb
    newTag: 2.25.1-pg16
