---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stream-analytics-store
  namespace: stream-analytics-system
  labels:
    app.kubernetes.io/name: stream-analytics-store
    app.kubernetes.io/component: store
    app.kubernetes.io/part-of: stream-analytics
    app.kubernetes.io/managed-by: argocd
automountServiceAccountToken: false
