---
apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-config
  namespace: data-management
  labels:
    app.kubernetes.io/name: clickhouse
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: stream-analytics
    app.kubernetes.io/managed-by: argocd
data:
  listen.xml: |
    <yandex>
      <listen_host>0.0.0.0</listen_host>
    </yandex>
  stream-analytics-user.xml: |
    <clickhouse>
      <users>
        <default remove="remove"/>
        <default>
          <profile>default</profile>
          <networks>
            <ip>10.0.0.0/8</ip>
            <ip>127.0.0.1</ip>
          </networks>
          <password from_env="CLICKHOUSE_PASSWORD"/>
          <quota>default</quota>
          <access_management>1</access_management>
        </default>
      </users>
    </clickhouse>
