---
apiVersion: v1
kind: Service
metadata:
  name: stream-analytics-processor
  namespace: stream-analytics-system
  labels:
    app.kubernetes.io/name: stream-analytics-processor
    app.kubernetes.io/component: processor
    app.kubernetes.io/part-of: stream-analytics
    app.kubernetes.io/managed-by: argocd
spec:
  selector:
    app: stream-analytics-processor
  ports:
    - port: 80
      name: service
      targetPort: service
      protocol: TCP
