---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stream-analytics-client
  namespace: stream-analytics-client
  labels:
    app.kubernetes.io/name: stream-analytics-client
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: stream-analytics
    app.kubernetes.io/managed-by: argocd
automountServiceAccountToken: false
