#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

REPORT_DIR=".context/evidence/runtime-gate"
GO_CACHE_DIR="${SOAK_GO_CACHE:-/tmp/go-build}"
FULL_MODE=0
KEEP_STACK=0

while [[ $# -gt 0 ]]; do
	case "$1" in
		--report-dir)
			REPORT_DIR="${2:?missing value for --report-dir}"
			shift 2
			;;
		--go-cache)
			GO_CACHE_DIR="${2:?missing value for --go-cache}"
			shift 2
			;;
		--full)
			FULL_MODE=1
			shift
			;;
		--keep-stack)
			KEEP_STACK=1
			shift
			;;
		*)
			echo "unknown argument: $1" >&2
			echo "usage: $0 [--report-dir <path>] [--go-cache <path>] [--full] [--keep-stack]" >&2
			exit 2
			;;
	esac
done

timestamp="$(date -u +%Y%m%dT%H%M%SZ)"
run_dir="${REPORT_DIR}/${timestamp}"
report_file="${run_dir}/report.md"
latest_report="${REPORT_DIR}/latest.md"
runner_log="${run_dir}/runner.log"

mkdir -p "$run_dir"

steps=()
statuses=()
durations=()

capture_artifacts() {
	local artifacts=(
		".context/evidence/w5-soak.txt"
		".context/evidence/vpvr-soak.txt"
		".context/evidence/c4-cold-roundtrip.txt"
	)
	if [[ "$FULL_MODE" -eq 1 ]]; then
		artifacts+=(
			".context/evidence/c4-pipeline-soak.txt"
			".context/evidence/c4-ws-delivery-soak.txt"
		)
	fi

	for artifact in "${artifacts[@]}"; do
		if [[ -f "$artifact" ]]; then
			cp "$artifact" "${run_dir}/$(basename "$artifact")"
		fi
	done
}

sha256_file() {
	shasum -a 256 "$1" | awk '{print $1}'
}

write_report() {
	local status="$1"
	local git_head
	local workspace_state
	git_head="$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")"
	workspace_state="$(git status --short | wc -l | tr -d ' ')"

	{
		echo "# Runtime Reliability Gate Report"
		echo
		echo "- timestamp_utc: ${timestamp}"
		echo "- status: ${status}"
		echo "- full_mode: ${FULL_MODE}"
		echo "- keep_stack: ${KEEP_STACK}"
		echo "- go_cache: ${GO_CACHE_DIR}"
		echo "- git_head: ${git_head}"
		echo "- workspace_changes: ${workspace_state}"
		echo
		echo "## Steps"
		echo
		echo "| Step | Status | Duration (s) | Log |"
		echo "|---|---|---:|---|"
		local i
		for i in "${!steps[@]}"; do
			echo "| ${steps[$i]} | ${statuses[$i]} | ${durations[$i]} | \`${steps[$i]}.log\` |"
		done
		echo
		echo "## Artifacts"
		echo
		echo "| Artifact | Bytes | SHA256 |"
		echo "|---|---:|---|"
		local artifact_file
		shopt -s nullglob
		for artifact_file in "${run_dir}"/*.txt; do
			echo "| \`$(basename "$artifact_file")\` | $(wc -c <"$artifact_file") | \`$(sha256_file "$artifact_file")\` |"
		done
		shopt -u nullglob
		echo
		echo "## Notes"
		echo
		echo "- Runner log: \`runner.log\`"
		echo "- Generated by: \`scripts/test/util/runtime-reliability-gate.sh\`"
	} >"$report_file"

	cp "$report_file" "$latest_report"
}

cleanup() {
	if [[ "$KEEP_STACK" -eq 1 ]]; then
		echo "[runtime-gate] keep-stack enabled; skipping make down" | tee -a "$runner_log"
		return
	fi
	echo "[runtime-gate] stopping compose stack (make down)" | tee -a "$runner_log"
	if make down > >(tee "${run_dir}/down.log") 2>&1; then
		echo "[runtime-gate] compose stack stopped" | tee -a "$runner_log"
	else
		echo "[runtime-gate] warning: make down failed" | tee -a "$runner_log"
	fi
}

run_step() {
	local name="$1"
	shift
	local start_ts end_ts duration status
	start_ts="$(date +%s)"
	echo "[runtime-gate] START ${name}: $*" | tee -a "$runner_log"
	if "$@" > >(tee "${run_dir}/${name}.log") 2>&1; then
		status="pass"
	else
		status="fail"
	fi
	end_ts="$(date +%s)"
	duration="$((end_ts - start_ts))"
	steps+=("$name")
	statuses+=("$status")
	durations+=("$duration")
	if [[ "$status" != "pass" ]]; then
		echo "[runtime-gate] FAIL ${name} (${duration}s)" | tee -a "$runner_log"
		return 1
	fi
	echo "[runtime-gate] PASS ${name} (${duration}s)" | tee -a "$runner_log"
	return 0
}

trap cleanup EXIT

echo "[runtime-gate] run directory: ${run_dir}" | tee -a "$runner_log"
echo "[runtime-gate] full mode: ${FULL_MODE}" | tee -a "$runner_log"

run_step "up-core" make up-core
run_step "smoke" make smoke
run_step "soak-check" make soak-check SOAK_GO_CACHE="${GO_CACHE_DIR}"

if [[ "$FULL_MODE" -eq 1 ]]; then
	run_step "soak-pipeline" make soak-pipeline SOAK_GO_CACHE="${GO_CACHE_DIR}"
	run_step "soak-ws-delivery" make soak-ws-delivery SOAK_GO_CACHE="${GO_CACHE_DIR}"
fi

capture_artifacts
write_report "pass"
echo "[runtime-gate] PASS report=${report_file}" | tee -a "$runner_log"
