#!/usr/bin/env bash
set -euo pipefail

msg_file="${1:-}"
if [[ -z "$msg_file" || ! -f "$msg_file" ]]; then
  echo "commit-msg hook requires commit message file path" >&2
  exit 1
fi

first_line="$(head -n1 "$msg_file" | tr -d '\r')"

# Allow merge/revert/fixup/squash commits generated by git.
if [[ "$first_line" =~ ^(Merge\ |Revert\ |fixup!\ |squash!\ ) ]]; then
  exit 0
fi

if [[ ${#first_line} -gt 72 ]]; then
  echo "Commit title too long (${#first_line}/72)." >&2
  exit 1
fi

pattern='^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\([a-z0-9._/-]+\))?(!)?: .+'
if ! [[ "$first_line" =~ $pattern ]]; then
  cat >&2 <<'ERR'
Invalid commit message.
Use Conventional Commits, e.g.:
  feat(workspace): add commit-msg hook
  fix(ci): make pipeline deterministic
ERR
  exit 1
fi
