---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flink-config
  namespace: analytics
  labels:
    app.kubernetes.io/name: flink
    app.kubernetes.io/component: stream-processor
data:
  flink-conf.yaml: |
    jobmanager.rpc.address: flink-jobmanager
    jobmanager.rpc.port: 6123
    jobmanager.memory.process.size: 1600m
    taskmanager.memory.process.size: 1728m
    taskmanager.numberOfTaskSlots: 2
    state.backend: filesystem
    state.savepoints.dir: file:///flink/checkpoints/savepoints
    state.checkpoints.dir: file:///flink/checkpoints
    rest.port: 8081
    rest.address: 0.0.0.0
    parallelism.default: 1
  log4j-console.properties: |
    rootLogger.level = INFO
    rootLogger.appenderRef.console.ref = ConsoleAppender
    appender.console.name = ConsoleAppender
    appender.console.type = CONSOLE
    appender.console.layout.type = PatternLayout
    appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss,SSS} %-5p %-60c %x - %m%n
