---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: analytics
resources:
  - serviceaccount.yaml
  - flink-config-configmap.yaml
  - sql-configmap.yaml
  - jobmanager-deployment.yaml
  - taskmanager-deployment.yaml
  - service.yaml
  - sql-init-job.yaml
