---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flink
  namespace: analytics
  labels:
    app.kubernetes.io/name: flink
    app.kubernetes.io/component: stream-processor
automountServiceAccountToken: false
