---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: raccoon-system
resources:
  - ../../base
replicas:
  - name: raccoon-processor
    count: 2
images:
  - name: raccoon-processor
    newTag: latest
