---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: raccoon-consumer
  namespace: raccoon-system
  labels:
    app.kubernetes.io/name: raccoon-consumer
    app.kubernetes.io/part-of: market-raccoon
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: raccoon-consumer
