---
apiVersion: v1
kind: Service
metadata:
  name: raccoon-consumer
  namespace: raccoon-system
  labels:
    name: raccoon-consumer
spec:
  selector:
    app: raccoon-consumer
  ports:
    - port: 80
      name: service
      targetPort: service
      protocol: TCP
