---
apiVersion: v1
kind: Service
metadata:
  name: stream-analytics-consumer
  namespace: stream-analytics-system
  labels:
    name: stream-analytics-consumer
spec:
  selector:
    app: stream-analytics-consumer
  ports:
    - port: 80
      name: service
      targetPort: service
      protocol: TCP
