---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: timescaledb
  namespace: data-management
  labels:
    app.kubernetes.io/name: timescaledb
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: stream-analytics
    app.kubernetes.io/managed-by: argocd
automountServiceAccountToken: false
